In [2]:
import numpy as np

In [18]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
a

b = np.zeros((10,10))

b


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [83]:
c = np.arange(0,16)
c

d = np.arange(0,6).reshape(3,2)
print(d)
print()
e = np.random.random(3)
e

f = np.arange(10,19).reshape(3,3)
print(f)
print()
#g = f * d
#print(g)
 
#g = d.dot(f)
print(c)

[[0 1]
 [2 3]
 [4 5]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [120]:
c[4::2]

f.shape=(9,1)
f

f= f.ravel()
f


array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [121]:
print(f)

[10 11 12 13 14 15 16 17 18]


In [1]:
import pandas as pd
